### ISSUE TITLE
Error when posting new story in production

### ISSUE THREAD

**Issue by seanwash** [seanwash/rodinia-report-next#4]
Noticing this when running `railway logs`:

```
ERROR: Creating Story PrismaClientValidationError: Unknown arg `topics` in data.topics for type StoryUncheckedCreateInput. Did you mean `id`?

    at Document.validate (/workspace/node_modules/@prisma/client/runtime/index.js:32546:19)
    at NewPrismaClient._executeRequest (/workspace/node_modules/@prisma/client/runtime/index.js:34652:17)
    at consumer (/workspace/node_modules/@prisma/client/runtime/index.js:34597:23)
    at /workspace/node_modules/@prisma/client/runtime/index.js:34599:47
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at NewPrismaClient._request (/workspace/node_modules/@prisma/client/runtime/index.js:34599:25)
    at Object.then (/workspace/node_modules/@prisma/client/runtime/index.js:34707:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  clientVersion: '2.25.0'
}
```

Things I've checked:

- [x] Both dev and production db's are at the same migration level
- [x] Tried submitting a story at dev.rodinia.report, it worked
- [x] Does `prisma generate` need to be part of the build pipeline?

---

I tried submitting the story a few times, I think it actually has something to do with the topic select. The story submitted fine when I deliberately selected a topic and then while the topic was selected, clicked submit. Note though, that I'm having trouble reproducing this locally in dev.

---

Got it, I added some light debugging around adding a story and it looks like somehow the tag values are getting messed up: 
![CleanShot 2021-06-22 at 20 56 41@2x](https://user-images.githubusercontent.com/428033/123033330-71a61200-d39c-11eb-9896-7a37f6a77070.png)

**Comment by seanwash** [comment]
Closing, fixed directly on the main branch :/

The gist is that something's a bit off with `new UrlSearchParams` on the node side. The fix was to just send JSON.
